### ISSUE TITLE
Teaser page

### ISSUE THREAD

**Issue by replygirl** [BSA-US/dual-power-app#1]
During development, we should have a teaser page with:
- [x] Project overview
- [x] Explanation of a Dual Power Project
- [x] Links to BSA, GitHub, etc.
- [ ] Early branding

**Comment by 2ndline** [comment]
Could we consider displaying the roadmap as well? Dunno what level of transparency we want to share with users, and could reduce support emails asking about future features

**Comment by mooooooooooooooon** [comment]
it's public here, we could start with a link or [pull from the api](https://developer.github.com/v3/projects/)

**Comment by sorcerix** [comment]
@replygirl closed this with #15
