### ISSUE TITLE
Wiki Appendix

### ISSUE THREAD

**Issue by geetotes** [BSA-US/dual-power-app#11]
Here's a first pass at some definitions for the wiki appendix

### Worker Cooperative
A business owned by workers. Workers contribute labor to the cooperative and pariticpate in its financial success. Management decisions are democratic, on the priniciple of one worker, one vote.

### Small Business Development Center

Private consulting to start and grow small businesses.

### Community Land Trust

Community land trusts are a way to ensure long-term housing affordability. Instead of buying a home, prospective homeowners enter into a long-term lease with the community land trust. When it comes time to "sell", the homeowner is given a portion of the property value from the community land trust.

By seperating housing from land, the land trust preserves the affordability of a neighborhood.

[More info](https://community-wealth.org/strategies/panel/clts/index.html)

### Dual Power

Dual Power is a strategy, rather than an ideology, that builds alternative institutions grounded in direct democracy to confront the failures of the capitalist state. By both building these instituations and orgaizing them, we can build a grassroots base of *dual power* to challenge the existing base of state and capitalist power.

[More info](https://blacksocialists.us/mumbo-jumbo)

### Dual Power Project

Some examples of past and present real-world dual power projects:

* [Cooperation Jackson](https://cooperationjackson.org/), Jackson, Mississippi - USA
* [Bâtiment 7](https://www.batiment7.org/), Montréal, Quebec - CANADA
* Municipality of Cherán, Mexico

[More info](https://roarmag.org/magazine/dual-power-then-and-now-from-the-iroquois-to-cooperation-jackson/)

### Solidarity Economy

An economic foundation that seeks to improve the quality of life of a community on the basis of solidarity. A solidarity economy strengthens dual power institutions.

[More info](https://ussen.org/)

### Cooperation Jackson

A network of cooperatives and worker-owned, democratically self-managed enterprieses in Jackson Mississippi.

[More info](https://cooperationjackson.org/)

### BSA

Founded in 2018, Black Socialists in America (BSA) is a coalition of anticapitalist, internationalist Black Americans who believe that the workers should control the means of production in a democratic and decentralized fashion ([see here](https://www.marxists.org/archive/fromm/works/1961/man/ch06.htm)).

We are a nonsectarian, "Scientific Socialist" organization ([see here](https://www.marxists.org/archive/marx/works/1880/soc-utop/ch02.htm)) made up of people who identify as many different things under the “Hard Left” umbrella, however we do not support egoists or insurrectionists, nor do we support highly centralized leadership ([see here](https://www.marxists.org/archive/brinton/1970/workers-control/index.htm)) or State Capitalism ([see here](https://www.marxists.org/archive/pannekoe/1936/dictatorship.htm) and [here](https://www.marxists.org/archive/miasnikov/1930/latest-deception/ch05.htm)).

**Comment by replygirl** [comment]
moving to #12
