### ISSUE TITLE
NPM package 'now' has been deprecated

### ISSUE THREAD

**Issue by EricSEkong** [BSA-US/dual-power-app#49]
The package noted in the on setup steps of the README.md has now been deprecated and should be replaced with something else: 

https://www.npmjs.com/package/now

The page above recommends a package called:

https://www.npmjs.com/package/vercel

**Comment by replygirl** [comment]
They are the same package, just moved to a new place since the maintainer got big VC $$$. Feel free to PR, otherwise it'll get found-and-replaced some time soon
