### ISSUE TITLE
DPP proposals

### ISSUE THREAD

**Issue by replygirl** [BSA-US/dual-power-app#5]
Unregistered users can submit & view proposals for dual power projects.

###### Tasks:
- [ ] Typeform setup
  - [ ] **Discussion:** Form fields
  - [ ] Form
  - [ ] Theme

###### Views:
- [ ] Index
  - [ ] List view
  - [ ] Map view
- [ ] DPP
- [ ] Propose a DPP

**Comment by 2ndline** [comment]
Would we need an approval screen, or is that in a separate issue

**Comment by mooooooooooooooon** [comment]
I noted up top that we need to have a discussion about that process, but trying to type up my thoughts I think I just realized it may benefit from being its own issue
