### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by replygirl** [BSA-US/dual-power-app#61]
- [ ] Replace references to Zeit & Now with Vercel
- [ ] Note Fauna as experimental
- [ ] Remove reference to wiki
- [ ] Mention Open Design and link to https://dualpower.app/open-design
- [ ] Replace rebase guide with link to a good third-party resource
- [ ] Update formerly `master` branch links to `main`

**Comment by jvbreen1** [comment]
https://github.com/BSA-US/dual-power-app/pull/88 fixes some of these, namely the `main` part
