### ISSUE TITLE
Update /open-design content

### ISSUE THREAD

**Issue by replygirl** [BSA-US/dual-power-app#89]
- [x] Replace "Open Design" with "Open Design + Build" in app header (nav link)
- [x] Replace "Open Design" with "Open Design + Build" in page header (the big guy)
- [x] Remove "with Manhattan Hydraulics"
- [x] Add separate paragraph mentioning Manhattan Hydraulics collaboration (something like "Open Design + Build started as a collaboration with Manhattan Hydraulics to...")
- [x] Add BSA star and Manhattan Hydraulics "MH" logo in a row below the text (I can provide svgs)
  - [ ] Any other parties we should list? DR?
  - [x] Consider adding `unplugin-auto-import` and `unplugin-icons` to the app

**Comment by cedrycm** [comment]
I can take care of this issue! I think I still need access to the repo though

**Comment by replygirl** [comment]
@cedrycm oh sick. i know you mentioned you might be busy again with work by now, but either way i'm giving you write access now

**Comment by cedrycm** [comment]
@replygirl  got access! ty

**Comment by cedrycm** [comment]
@replygirl should we change the route for the open-design page or is it fine as is? 
Also could you send over the svgs for the logos?

**Comment by replygirl** [comment]
@cedrycm let's leave the route the same for now, it's shorter and we won't have to worry about a route alias for older links to the page.

here are the assets, `*-glyph.svg` is just a logo on its own and `*-icon.svg` puts the glyph in a perfect square. use your judgment for which looks better, but put all 4 in the public directory whether you use em or not, we might need them later

[od-svg.zip](https://github.com/BSA-US/dual-power-app/files/7555362/od-svg.zip)
